name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://get.pixelexperience.org/Y2pwSUNkTVFPSEJyMXJsamxQcUExUGptWE1CaVg2RE1TWTNVc1JsKzJuajc2UEVJUXdtckUwV3dSUUVFKzFlZlA4aHF1eGJDa2Z2R2NjbnBIY2FtMkU0R1dCK2JhZk9pbG16ZzQxM3g1S1Buc3U4NFBUN0gyY1B0VlhraHlkNnc=/PixelExperience_land-11.0-20210422-1522-OFFICIAL.zip
  ROM_NAME: Pixel
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with Xiaoxin script
         run: |
              cd ErfanGSIs
              mkdir ./output
              wget https://github.com/xiaoxindada/SGSI-build-tool/blob/12/SGSI.sh
              sudo bash setup-xiaoxin.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -c -b $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
